# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-30 18:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_post_publicado'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='slug',
            field=models.SlugField(blank=True, max_length=500, null=True),
        ),
    ]
